apiVersion: 1

datasources:
  - name: HelmLog API
    type: marcusolsson-json-datasource
    uid: helmlog-api
    url: http://localhost:3002
    access: proxy
    isDefault: false
    editable: false

  - name: Loki
    type: loki
    uid: loki
    url: http://127.0.0.1:3100
    access: proxy
    isDefault: false
    editable: false
